### ISSUE TITLE
NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by KamilChytil** [Razenpok/BreakInfinity.cs#16]
Hello
And I wanted to start adding numbers popped up error NotImplementedException: the method or operation is not implemented.
BreakInfinity.BigDouble.op_Explicit (BreakInfinity.BigDouble v)
and it doesn't add or display anything anywhere.
Here when I click on the error 
 public static explicit operator float(BigDouble v)
        {
            throw new NotImplementedException();
        }

**Comment by Razenpok** [comment]
Hi @KamilChytil 

What's your code which throws this exception?

**Comment by KamilChytil** [comment]
[BigDouble.zip](https://github.com/Razenpok/BreakInfinity.cs/files/9374141/BigDouble.zip)
in this script
line 304

**Comment by Razenpok** [comment]
Where did you get that file? It is different from the one in the repository
https://github.com/Razenpok/BreakInfinity.cs/blob/master/BreakInfinity/BigDouble.cs#L304

**Comment by KamilChytil** [comment]
ohhh thans so much it works 
Question
how do i convert float to double ?

        if (coins / clickUpgrade1Cost < 0.01)
        {
            clickUpgrade1Bar.fillAmount = 0;
        }
        else if (coins / clickUpgrade1Cost >  10)
        {
            clickUpgrade1Bar.fillAmount = 1;
        }
        else
            clickUpgrade1Bar.fillAmount = (float)(coins / clickUpgrade1Cost);
the problem is in clickUpgrade1Bar.fillAmount = (float)(coins / clickUpgrade1Cost);

**Comment by Razenpok** [comment]
Hmm, try changing it to

```csharp
clickUpgrade1Bar.fillAmount = (float)(coins / clickUpgrade1Cost).ToDouble();
```

Let me know if it works

**Comment by Razenpok** [comment]
Alright, I'm closing issue if there's no more problems
