### ISSUE TITLE
Can't Deserialize with Newtonsoft.json in Unity v2022.3.27f1 (newtonsoft version 3.0.2)

### ISSUE THREAD

**Issue by Lorenzo0402** [Razenpok/BreakInfinity.cs#22]
Serialization works perfectly fine with Newtonsoft.Json.JsonConvert.SerializeObject(data)

De-serialization does not work. BigDouble values are "0". example.json looks like this:
{
  "Money": {
    "Mantissa": 1.421,
    "Exponent": 23  }
}

**Comment by Lorenzo0402** [comment]
Maybe this is a issue with Newtonsoft.json? not sure, im posting it there too

**Comment by Lorenzo0402** [comment]
Changed the code from being a private mantissa and exponent to being public, changing the constructors aswell. now it works. 
closing this thread.

**Comment by izzyis-dev** [comment]
> Changed the code from being a private mantissa and exponent to being **public**, changing the constructors aswell. now it works. closing this thread.

Thank you, I was having the same problem and that fixed the issue I was having. Another workaround I found was adding [JsonProperty] attribute on top of the fields.
