### ISSUE TITLE
How can I find a %?

### ISSUE THREAD

**Issue by rasm685p** [Razenpok/BreakInfinity.cs#3]
I'm trying to use a bigdouble number in a progress bar but it might not be possible? I wanted to do something like this:
```
BigDouble num1 = 1000;
BigDouble num2 = 100;

BigDouble num3 = (num2 / num1) * 100;

int num4 = Convert.ToInt32(num3);
hp1.Value = num4;
hp1.Maximum = 100;
```
Is this even possible? I tried converting it to a string and then back, but the number gets too large. 

- If possible, would you mind showing me how? Thank you!

**Comment by Patashu** [comment]
try `double num4 = num3.ToDouble()` or `int num4 = (int)Math.Round(num3.ToDouble())`

**Comment by rasm685p** [comment]
@Patashu Thank you! I can finally continue my "game" 👍

**Comment by rasm685p** [comment]
I'll close this. Thanks for making the BreakInfinity library

**Comment by Razenpok** [comment]
Yay! Sorted before I even wake up; cheers.

Side notes:
- As @Patashu said, `.ToDouble` and `(int)` casting are preferable. It actually applies to most of other C# code - you can do 99% of type conversions without `Convert` class (iirc, it was introduced to handle some edge cases)
- @rasm685p I'll take a guess that `hp1.Value` won't be very big, based on `hp1.Maximum = 100;`. Are you sure you really want to use `BigDouble` in this case?

**Comment by rasm685p** [comment]
@Razenpok You might want to look at my github repository "Monster Hunt" if you got the time? But yeah i figured out that bigdouble isn't the best solution for everything.

**Comment by Razenpok** [comment]
Looks okay so far, though I'd suggest two things:
- You don't need `BigDouble` unless you are working with **really** big numbers - you'll know when you will need it. But until then, use stock `double` or `float`.
- Try out some code-quality tools (like ReSharper or CodeMaid) - your code will benefit from them tremendously.
