### ISSUE TITLE
Add [Serializable] attribute

### ISSUE THREAD

**Issue by Patashu** [Razenpok/BreakInfinity.cs#5]
I don't think you need to do anything else, since it should serialize fine by default

**Comment by Razenpok** [comment]
Not really, I would need to change Mantissa and Exponent from properties to fields, but I get your point.

**Comment by Patashu** [comment]
Having a guy in AD NG+3 #coding channel who's trying to get their save data to serialize, so I figure having it serialize by default would eliminate at least one hurdle

**Comment by Razenpok** [comment]
Ye, but without custom editor it would still be a hussle to edit. Shouldn't be big of a trouble, I'll take a look this weekend.

**Comment by Razenpok** [comment]
>hussle

lol

**Comment by NightStormYT** [comment]
To add onto Patashu ^ I'm trying to save BigDoubles to a json save via FileStream, but since BigDoubles aren't serializeable, they won't save nor load. Sample code: https://pastebin.com/5fVjYpWN

**Comment by NightStormYT** [comment]
Fixed Version of breakinfinity.cs: https://pastebin.com/FM2W3VnZ
